### ISSUE TITLE
建议接口定义时ServiceProvider不是必须的

### ISSUE THREAD

**Issue by huanghanhuikkx** [fengjiachun/Jupiter#11]
定义接口时必须使用ServiceProvider，这种强类型的方式在有些场景缺乏一些灵活性。接口定义的工程必须依赖Jupiter 的包，这样接口给到别处会造成一些不便。所以希望可以支持弱类型的配置方式而不是一定要使用ServiceProvider.

**Comment by fengjiachun** [comment]
@huanghanhuikkx 十分感谢您的建议, ServiceProvider强依赖在1.2.2版本中已经去除
