### ISSUE TITLE
org.jupiter.common.util.NetUtil类IP_PATTERN正则匹配问题

### ISSUE THREAD

**Issue by xingguang2013** [fengjiachun/Jupiter#15]
Pattern.compile("\\d{1,3}(\\.\\d{1,3}){3,5}$");
此正则对于IP地址的匹配上{3,5}存在问题，建议修改为Pattern.compile("\\d{1,3}(\\.\\d{1,3}){3}$");

**Comment by fengjiachun** [comment]
[https://github.com/fengjiachun/Jupiter/pull/16/commits/6af661bedbd024daeb4040076f11523584d9c2d0](url)
