### ISSUE TITLE
Jupiter的Spring xml配置：consumer bean配置serializerType属性失效

### ISSUE THREAD

**Issue by xingguang2013** [fengjiachun/Jupiter#27]
在spring的[jupiter:consumer bean](https://github.com/fengjiachun/Jupiter/blob/master/jupiter-example/src/main/resources/spring-consumer.xml)中配置serializerType属性，但在[JupiterBeanDefinitionParser#parseJupiterConsumer](https://github.com/fengjiachun/Jupiter/blob/master/jupiter-spring-support/src/main/java/org/jupiter/spring/schema/JupiterBeanDefinitionParser.java)方法中，并没有对serializerType属性设置值，导致serializerType属性失效

**Comment by fengjiachun** [comment]
非常感谢 @xingguang2013
