### ISSUE TITLE
为什么要提供那么多种序列化方式？

### ISSUE THREAD

**Issue by leoge0113** [fengjiachun/Jupiter#36]
就提供一种性能最好的不可以吗？
提供多种的原因是什么？

**Comment by fengjiachun** [comment]
性能只算其中一个指标, 有的场景个人认为性能也不是第一位的; 其他指标比如兼容性, 跨语言等等, jupiter里每个序列化/反序列化实现都有各自的特点

**Comment by leoge0113** [comment]
谢谢jiachun
