### ISSUE TITLE
整合disruptor问题

### ISSUE THREAD

**Issue by xingguang2013** [fengjiachun/Jupiter#4]
看您的common包中有对disruptor的封装，但在实际代码中没有搜索到使用的地方，请问您会对此应用在相关模块中么

**Comment by fengjiachun** [comment]
您好, 有使用到的, 不过默认不会使用到, 是基于SPI配置的

[DisruptorExecutorFactory](https://github.com/fengjiachun/Jupiter/blob/master/jupiter-rpc/src/main/java/org/jupiter/rpc/executor/DisruptorExecutorFactory.java)

上面的executorFactory为disruptor实现, 可以在[DefaultProviderProcessor](https://github.com/fengjiachun/Jupiter/blob/master/jupiter-rpc/src/main/java/org/jupiter/rpc/provider/processor/DefaultProviderProcessor.java) / [DefaultConsumerProcessor](https://github.com/fengjiachun/Jupiter/blob/master/jupiter-rpc/src/main/java/org/jupiter/rpc/consumer/processor/DefaultConsumerProcessor.java)中使用(基于SPI);

配置见这里(修改为org.jupiter.rpc.executor.DisruptorExecutorFactory即可):
[org.jupiter.rpc.provider.processor.ProviderExecutorFactory](https://github.com/fengjiachun/Jupiter/blob/master/jupiter-rpc/src/main/resources/META-INF/services/org.jupiter.rpc.provider.processor.ProviderExecutorFactory)
或
[org.jupiter.rpc.consumer.processor.ConsumerExecutorFactory](https://github.com/fengjiachun/Jupiter/blob/master/jupiter-rpc/src/main/resources/META-INF/services/org.jupiter.rpc.consumer.processor.ConsumerExecutorFactory)

**Comment by xingguang2013** [comment]
您好，看到了，还是没有仔细阅读您的代码，谢谢您的回复。
看您的代码感觉有很多学习的地方，感谢
