### ISSUE TITLE
zookeeper挂了后重启，provide和consumer的处理行为是什么？

### ISSUE THREAD

**Issue by leoge0113** [fengjiachun/Jupiter#40]
1. provide能否注册新服务？
2. 服务不可以是通过zookeeper判断的吗？如果是原来注册的服务可用性功能是否会受到影响？
3. consumer端的watcher是否还可用？
给点您当时设计时的一些想法，代码我还正在看。
先谢谢

**Comment by fengjiachun** [comment]
你好:
1. zk挂了就不能注册新服务了
2. 原有服务只要不重启就不影响, 本地都有, 重启就没有了
3. zk挂了会自动重连, zk恢复后会重新连上
