### ISSUE TITLE
DefaultInvokeFuture#TimeoutScanner优化

### ISSUE THREAD

**Issue by fengjiachun** [fengjiachun/Jupiter#62]
目前是遍历chm来查找超时future, 有一定竞争

**Comment by scanry** [comment]
那么我们再回到问题的本质:就是删除异步调用future。也就是在客户端调用服务端客户端没有收到服务响应，那么超时后uture会一直占用cache。
如果在发起调用后将要监听的异步future票据插入时间轮队列的时间O(lgn)接收不了的话，那么还可以加一层普通FIFO队列，然后单独一个守护线程处理这个future票据将它插入时间轮队列，这样发起调用线程的时间花费那么就变成O(1)。
这样的话是不是也减少了发起调用前将future插入cache 同 扫描cache中过期future线程 的 锁竞争？

**Comment by Coneboy-k** [comment]
使用 类似于netty 的Channel idle 的检测机制（HashedWheelTimer）如何？

**Comment by fengjiachun** [comment]
@Coneboy-k 不错, 是计划用hash时间轮试一试

**Comment by fengjiachun** [comment]
@scanry @Coneboy-k 对于队列容量是个考验, 因为future只有超时的情况才会被移除

**Comment by fengjiachun** [comment]
future在chm中的时候只要响应回复了就可以移除

**Comment by Coneboy-k** [comment]
我的CHM  存future不变。
增加一个Futur超时管理的Service 。 Service的管理的超时对象，是继承于AbsTimerItem 。  其中 AbsTimerItem有超时读和写的方法，最终在Service中可以封装成接口暴露给存future的CHM。这样写法耦合度很低。不需要改变太多代码
其中对应关系为 Service：timerObj：future=M:1:1  

PoolItemService.java
https://gist.github.com/Coneboy-k/9c7496abc45012f6943d2a94ffcfa93a    
AbsTimerItem.java
https://gist.github.com/Coneboy-k/4c0cc857425e32f80a8a0bf1739d28be


如果思路没问题，我尝试提交个PR
上面的还是参考大佬 netty idle的检测实现的。 :-)

**Comment by fengjiachun** [comment]
简单列一下数据, 先假设一个40w qps的系统(client), 超时时间平均为3秒 那么就有120w的future在队列中(时间轮是有队列的)
这个queue如果用数组实现(netty的实现不光是数组, 还有padding) 会占用较大连续内存, 如果用链表实现, 也会有大量的node节点
还有更严重的, 由于队列节点移除只能等到超时才移除, 如果因为长时间被强引用, 这些future进入了老年代…. 那么想被gc掉就不是一时半会的事情了, 别忘了future还会引用着rpc的返回结果对象…..
这个空间换时间 … 牺牲的有些多

**Comment by fengjiachun** [comment]
经 @scanry 的提醒, 超时队列只存放invokeId, 然后再回到DefaultInvokeFuture#roundFutures中查找future就可以了

**Comment by fengjiachun** [comment]
[忘了关联到这个issue上了](https://github.com/fengjiachun/Jupiter/commit/1f16f8c2760d51ac12f9a202ced1a8deb99fae73)

**Comment by fengjiachun** [comment]
@Coneboy-k 你给的链接打不开啊

**Comment by Coneboy-k** [comment]
@fengjiachun gist.github.com 貌似被墙了。挂个代理试试？
