### ISSUE TITLE
RandomLoadBalancer算法问题，两个节点，永远只能选择第一个

### ISSUE THREAD

**Issue by chywwq** [fengjiachun/Jupiter#71]
RT

**Comment by fengjiachun** [comment]
没有吧? 你用 org.jupiter.rpc.load.balance.RandomLoadBalancerTest 测试下看看?

**Comment by chywwq** [comment]
如果不设置weight，就会有问题

**Comment by fengjiachun** [comment]
能否明确说下? 我跑了单测的结果是, weight不管设置不设置都出现不了你描述的结果 @chywwq

**Comment by chywwq** [comment]
没有问题。
