### ISSUE TITLE
对Reflects.fastInvoke benchmark结果的疑惑

### ISSUE THREAD

**Issue by uvletter** [fengjiachun/Jupiter#75]
feng大好久不见。
最近对Jupiter provider调用本地方法的部分比较感兴趣，研究了下源码觉得实现十分巧妙，后来在网上看到ReflectAsm也是这么设计的一个高性能反射框架，于是萌生了对这两个做benchmark的想法，但是结果似乎是ReflectAsm更优。

benchmark代码贴在下面：

        
        <dependency>
            <groupId>com.esotericsoftware.reflectasm</groupId>
            <artifactId>reflectasm</artifactId>
            <version>1.05</version>
        </dependency>

    public static class Mock{
        static int i = 1;
        public int get() {
            return i++;
        }
    }

    public static void main(String[] args) {
        int times = 10000000;//循环执行次数
        Mock mock = new Mock();
        MethodAccess access = MethodAccess.get(Mock.class);
        int index = access.getIndex("get");
        Class[] classes = new Class[]{};
        Object result=null;

        //warmup
        System.out.println("Warmup");
        long t1 = System.currentTimeMillis();
        for (int i = 0; i< times; i++) {
            result = Reflects.fastInvoke(mock, "get", classes, null);
        }
        long t2 = System.currentTimeMillis();
        System.out.println(String.format("fastInvoke:%d %d",t2-t1,result));
        for (int i = 0; i< times; i++) {
            result = Reflects.invoke(mock, "get", classes, null);
        }
        long t3 = System.currentTimeMillis();
        System.out.println(String.format("invoke:%d %d",t3-t2,result));
        for (int i = 0; i< times; i++) {
            result = mock.get();
        }
        long t4 = System.currentTimeMillis();
        System.out.println(String.format("native:%d %d",t4-t3, result));
        for (int i = 0; i< times; i++) {
            result = access.invoke(mock, "get");
        }
        long t5 = System.currentTimeMillis();
        System.out.println(String.format("ReflectASM:%d %d",t5-t4,result));
        for (int i = 0; i< times; i++) {
            result = access.invoke(mock, index);
        }
        long t6 = System.currentTimeMillis();
        System.out.println(String.format("ReflectASM with index:%d %d",t6-t5, result));
        for (int i = 0; i< times; i++) {
            result = access.invoke(mock, access.getIndex("get", classes));
        }
        long t7 = System.currentTimeMillis();
        System.out.println(String.format("ReflectASM with full match:%d %d",t7-t6, result));

        //benchmark begin
        for (int j = 1; j <= 10; j++) {
            System.out.println();
            System.out.println("iterate " + j);
            System.out.println();
            t1 = System.currentTimeMillis();
            for (int i = 0; i < times; i++) {
                result =  Reflects.fastInvoke(mock, "get", classes, null);
            }
            t2 = System.currentTimeMillis();
            System.out.println(String.format("fastInvoke:%d %d", t2 - t1, result));
            for (int i = 0; i < times; i++) {
                result =  Reflects.invoke(mock, "get", classes, null);
            }
            t3 = System.currentTimeMillis();
            System.out.println(String.format("invoke:%d %d", t3 - t2, result));
            for (int i = 0; i < times; i++) {
                result =  mock.get();
            }
            t4 = System.currentTimeMillis();
            System.out.println(String.format("native:%d %d", t4 - t3, result));
            for (int i = 0; i < times; i++) {
                result =  access.invoke(mock, "get");
            }
            t5 = System.currentTimeMillis();
            System.out.println(String.format("ReflectASM:%d %d", t5 - t4, result));
            for (int i = 0; i < times; i++) {
                result =  access.invoke(mock, index);
            }
            t6 = System.currentTimeMillis();
            System.out.println(String.format("ReflectASM with index:%d %d", t6 - t5, result));
            for (int i = 0; i < times; i++) {
                result =  access.invoke(mock, access.getIndex("get", classes));
            }
            t7 = System.currentTimeMillis();
            System.out.println(String.format("ReflectASM with full match:%d %d", t7 - t6, result));
        }
    }

结果：
Warmup
fastInvoke:227 10000000
invoke:2033 20000000
native:51 30000000
ReflectASM:62 40000000
ReflectASM with index:55 50000000
ReflectASM with full match:72 60000000

iterate 1

fastInvoke:109 70000000
invoke:1339 80000000
native:55 90000000
ReflectASM:66 100000000
ReflectASM with index:55 110000000
ReflectASM with full match:65 120000000

iterate 2

fastInvoke:142 130000000
invoke:1336 140000000
native:31 150000000
ReflectASM:36 160000000
ReflectASM with index:31 170000000
ReflectASM with full match:44 180000000

iterate 3

fastInvoke:97 190000000
invoke:1302 200000000
native:30 210000000
ReflectASM:36 220000000
ReflectASM with index:31 230000000
ReflectASM with full match:44 240000000

iterate 4

fastInvoke:95 250000000
invoke:1268 260000000
native:32 270000000
ReflectASM:35 280000000
ReflectASM with index:34 290000000
ReflectASM with full match:44 300000000

iterate 5

fastInvoke:95 310000000
invoke:1271 320000000
native:31 330000000
ReflectASM:35 340000000
ReflectASM with index:31 350000000
ReflectASM with full match:45 360000000

iterate 6

fastInvoke:95 370000000
invoke:1266 380000000
native:32 390000000
ReflectASM:36 400000000
ReflectASM with index:31 410000000
ReflectASM with full match:45 420000000

iterate 7

fastInvoke:95 430000000
invoke:1256 440000000
native:31 450000000
ReflectASM:35 460000000
ReflectASM with index:31 470000000
ReflectASM with full match:44 480000000

iterate 8

fastInvoke:95 490000000
invoke:1260 500000000
native:32 510000000
ReflectASM:36 520000000
ReflectASM with index:31 530000000
ReflectASM with full match:44 540000000

iterate 9

fastInvoke:96 550000000
invoke:1250 560000000
native:31 570000000
ReflectASM:35 580000000
ReflectASM with index:32 590000000
ReflectASM with full match:44 600000000

iterate 10

fastInvoke:94 610000000
invoke:1245 620000000
native:31 630000000
ReflectASM:35 640000000
ReflectASM with index:32 650000000
ReflectASM with full match:44 660000000

可以看到通过预计算的索引调用的ReflectASM跟直接调用速度几乎一样，不考虑方法重载的ReflectASM速度略慢（即只通过方法名而不通过参数类型匹配方法），使用参数类型匹配的ReflectASM再慢一点，fastInvoke最慢，是前者的两倍多。对比了一下两者的源码，方法匹配部分的逻辑是一样的，但是ASM部分没研究，因为看不懂...

feng大可以检查下我的benchmark逻辑有没有问题 : )

**Comment by uvletter** [comment]
jdk1.8.0_151，Windows10环境，电脑配置渣机就不贴了

**Comment by fengjiachun** [comment]
@uvletter 可不可以用JMH测一把? 类似 https://github.com/fengjiachun/Jupiter/blob/master/jupiter-common/src/test/java/org/jupiter/common/util/MethodInvokeBenchmark.java

对于ReflectASM : MethodAccess.get(Mock.class)需要每次都调用, index也需要每次都计算, 不要缓存为局部变量, 否则就不公平了
对于反射: 需要把Method对象缓存下来, 要么也很不公平

另外, 如果你仔细看了jupiter中FastMethodAccessor这个类, 一定会发现, 思路是和ReflectASM一样的, 其实就是参考ReflectASM来的, 理论上他俩个性能不会有太大差距的, 最初jupiter是直接依赖ReflectASM, 后来jupiter精简依赖的jar, 就写了FastMethodAccessor, 去掉了对ReflectASM的依赖(毕竟jupiter也是作为lib提供给用户使用的, 对其他三方jar依赖越少越好)

**Comment by fengjiachun** [comment]
如果你用JMH测下来的数据还是和ReflectASM有较大差距, 可不可以提个PR把测试代码提交到 jupiter-exmaple的moudle中?

**Comment by uvletter** [comment]
这一阵要忙大促，十一我抽时间补上
