### ISSUE TITLE
[feature request]增加更优雅的异步调用方式

### ISSUE THREAD

**Issue by sandogeek** [fengjiachun/Jupiter#82]
新增InvokeType.AUTO，当rpc调用返回值为CompletionStage的子类时自动使用异步调用，否则采用同步调用。（这需要InvokeFuture增加方法以便在providerImpl的函数中返回已complete的CompletionStage。）

**Comment by fengjiachun** [comment]
demo 见 https://github.com/fengjiachun/Jupiter/blob/feat/v1.3/jupiter-example/src/main/java/org/jupiter/example/round/AutoJupiterClient.java

目前还处于测试阶段，欢迎试用以及反馈 @sandogeek

**Comment by fengjiachun** [comment]
目前已知问题：
1、 CompletableFuture 无法被 hessian/java 序列化（因为 CompletableFuture 没有 implement java.io.Serializable）
这个问题暂时不想理他，我觉得不是问题，使用 InvokeType.AUTO 必须选择 protostuff 或 kryo 序列化类型

**Comment by fengjiachun** [comment]
并不是不可解决这个问题，可以改为 CompletableFuture 不参与序列化/反序列化， 在框架内 mock 掉，但是这样又存在对 InvokeType.SYNC 的兼容性问题
先暂定不解决与 hessian 的不兼容问题，不是很有价值

**Comment by fengjiachun** [comment]
已在 1.3.0 中支持
